# Generated by Django 3.1.5 on 2021-01-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20210112_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='discord_id',
            field=models.BigIntegerField(),
        ),
    ]
