# Generated by Django 3.1.5 on 2021-01-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20210114_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Calls',
            new_name='GameCalls',
        ),
        migrations.RenameModel(
            old_name='Game_Secrets',
            new_name='GameSecrets',
        ),
        migrations.RenameModel(
            old_name='Game_Tickets',
            new_name='GameTickets',
        ),
    ]
