# Generated by Django 3.1.5 on 2021-01-15 09:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20210114_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesecrets',
            name='secrets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None),
        ),
    ]
