# Generated by Django 3.1.5 on 2021-01-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20210115_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecalls',
            name='game_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='gamesecrets',
            name='game_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='gametickets',
            name='game_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='game_id',
            field=models.BigIntegerField(),
        ),
    ]
